name: Code Style

on:
  push:

jobs:
  typing:
    name: MyPy (typing)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install -r requirements.txt
          pip install mypy==1.19.1

      - name: Install package
        run: |
          pip install .

      - name: Run MyPy
        run: |
          make mypy

  flake8:
    name: Flake8 (style check)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install -r requirements.txt
          pip install flake8==7.3.0

      - name: Install package
        run: |
          pip install .

      - name: Run MyPy
        run: |
          make flake8
